[tools]
go = "1.27.1"

[env]
_.path = ["{{config_root}}/bin"]

[tasks.test]
run = "go test ./..."

[tasks.racing]
run = "go run ./cmd/racing"
env = { _.file = ".env" }

[tasks.build]
run = "go build -o bin/racing ./cmd/racing"
